### ISSUE TITLE
Updating the module to latest version will create additional fstab entries for the same swapfile

### ISSUE THREAD

**Issue by mattock** [petems/petems-swap_file#20]
Upgrading the module to latest version produces additional fstab entry/entries for the same swapfile:

```
# Old
/swapfile0  swap    swap    defaults    0   0
# New
/swapfile0  /swapfile0  swap    defaults    0   0
``` 
I suspect this is related to the introduction of swap_file::files resource, but I have not looked at this closely.

**Comment by petems** [comment]
@mattock Is this the usecase of using the old module, upgrading, then running puppet again?

**Comment by petems** [comment]
Closing this as no update in a year, any problems or reproducible scenario, I will re-open

**Comment by mattock** [comment]
I think this problem was introduced by refactoring of the module. Users who have never used the earlier non-refactored module are not affected, so I think it is reasonable to close this.
