### ISSUE TITLE
Directory not empty @ dir_s_rmdir

### ISSUE THREAD

**Issue by gesinn-it** [petems/petems-swap_file#63]
# Environment:
* puppet 4.x
* mod 'petems/swap_file', '3.0.1'

# Steps to reproduce:
puppet apply with
```
swap_file::files { 'default':
  ensure   => present,
}
```

I get:
```
/usr/lib/ruby/2.3.0/fileutils.rb:1445:in `rmdir': Directory not empty @ dir_s_rmdir - /tmp/vagrant-puppet/environments/default/modules/swap_file (Errno::ENOTEMPTY)
```

**Comment by petems** [comment]
Ignore the gitmagic thing, thats supposed to be only on my branches 👎 

Can you link the `Vagrantfile` you're using for that? It looks like a Vagrant error rather than a module error

**Comment by gesinn-it** [comment]
uuuh, sorry, this seems to be an issue with Librarian Puppet...
