### ISSUE TITLE
cannot remove xxx.pack: Device or resource busy

### ISSUE THREAD

**Issue by gesinn-it** [petems/petems-swap_file#65]
Environment:
- vagrant 1.8.4
- puppet 4.5.2
- librarian-puppet 2.2.3
- mod 'petems/swap_file', '3.0.1'
- host: Win 7
- guest: ubuntu/xenial64
- vagrant plugins (current versions): vagrant-vbguest vagrant-puppet-install vagrant-triggers

I'd like to do the following cleanup tasks with vagrant destroy:

```
  config.trigger.after :destroy do
    run "rm -Rf puppet/environments/default/.tmp/*"
    run "rm -Rf puppet/environments/default/.librarian/*"
    run "rm -f puppet/environments/default/Puppetfile.lock"
    run "rm -Rf puppet/environments/default/modules/*"
  end
```

However, `rm -Rf puppet/environments/default/modules/*` fails with the following message:
`/usr/bin/rm: cannot remove 'puppet/environments/default/modules/swap_file/spec/fixtures/modules/stdlib/.git/objects/pack/pack-817ca3838f77e03f7d65ebde9778cba43a74a5de.pack': Device or resource busy`

I need to delete the remaining files in Windows. All other modules can be removed without any problem with the commands above.

Any idea?

**Comment by petems** [comment]
This is more of a Vagrant question I'm afraid, the module doesnt manage it's mounting within VM's, closing
