### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rmestrum** [petems/petems-swap_file#72]
Is a new release comming soon? I need the commit ced3b26bd11b6f9d02c8105cd6f61c5719fb4ac0 and this commit is not in release 3.0.2

**Comment by petems** [comment]
@rmestrum Sure, let me cut and release a new tag now

**Comment by petems** [comment]
v3.1.3 has been released to the forge, changelog here: https://forge.puppet.com/petems/swap_file/changelog

**Comment by rmestrum** [comment]
Thanks for creating a release that quick
